name: Update Milestone Data

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 3am/4am EST
  workflow_dispatch: # Allows you to click "Run" manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pandas requests nba_api

    - name: Run NBA & NHL Scanners
      env:
        # This line hands the secret to Python
        SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
      run: |
        python scan_nba_milestones_json.py
        python scan_nhl_milestones_json.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add *.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update stats" && git push)
